name: Code check

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - master

jobs:
  PylintCheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.x'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Running Pylint check
        run: |
          pylint $(git ls-files '*.py')
  Unit_Testing:
    needs: PylintCheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.x'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          pytest -m "unit" test_main.py

  name: Build and deploy a container to an Azure Web App

  Build_container:
    needs: Unit_Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${env.AZURE_TAG}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: Build_container

    steps:
      - name: Login to Azure
        run: docker login ${env.LOGIN} --username ${env.USERNAME} --password ${env.PASSWORD}

      - name: Push
        run: docker push -t ${env.AZURE_TAG}
